name: ci

on:
  push:
  pull_request:

jobs:
  ci-local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker compose CI
        run: |
          bash scripts/ci_local.sh

